version: '3.8'

networks:
  project:
    driver: bridge

services:
  nginx:
    container_name: shop-nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/symfony
    ports:
      - "8088:80"
    links:
      - php-fpm
    networks:
      - project

  php-fpm:
    container_name: shop-php
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/symfony
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      XDEBUG_SESSION: PHPSTORM
      PHP_IDE_CONFIG: "serverName=Shop-api"
    extra_hosts:
      - "host.docker.internal:$DOCKER_INTERNAL_IP"
      - "api.local:$DOCKER_INTERNAL_IP"
    networks:
      - project

  db:
    container_name: shop-db
    image: mysql:8
    command:
      --default-authentication-plugin=mysql_native_password
      --max_connections=666
      --bind-address=0.0.0.0
      --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: shop
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
    ports:
      - "13307:3307"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/init/my.cnf:/etc/mysql/my.cnf